// Code generated by go-wayland-scanner from virtual-keyboard-unstable-v1.xml. DO NOT EDIT.

// virtual_keyboard_unstable_v1 Protocol Copyright:
// Copyright © 2008-2011 Kristian Høgsberg
// Copyright © 2010-2013 Intel Corporation
// Copyright © 2012-2013 Collabora, Ltd.
// Copyright © 2018 Purism SPC
// SPDX-License-Identifier: MIT

package wlr_virtual_keyboard

import (
	"github.com/vcaesar/go-wayland/client"
	"golang.org/x/sys/unix"
)

// ZwpVirtualKeyboardV1 : virtual keyboard
//
// The virtual keyboard provides an application with requests which emulate
// the behaviour of a physical keyboard.
type ZwpVirtualKeyboardV1 struct {
	client.BaseProxy
}

// NewZwpVirtualKeyboardV1 creates a new ZwpVirtualKeyboardV1.
func NewZwpVirtualKeyboardV1(ctx *client.Context) *ZwpVirtualKeyboardV1 {
	zwpVirtualKeyboardV1 := &ZwpVirtualKeyboardV1{}
	ctx.Register(zwpVirtualKeyboardV1)
	return zwpVirtualKeyboardV1
}

// ZwpVirtualKeyboardV1InterfaceName is the wayland interface name.
const ZwpVirtualKeyboardV1InterfaceName = "zwp_virtual_keyboard_v1"

// ZwpVirtualKeyboardV1Error : error values
type ZwpVirtualKeyboardV1Error uint32

const (
	ZwpVirtualKeyboardV1ErrorNoKeymap ZwpVirtualKeyboardV1Error = 0
)

// Keymap sets the keyboard mapping via a file descriptor.
// format: keymap format (1 = XKB_V1)
// fd: keymap file descriptor
// size: keymap size in bytes
func (i *ZwpVirtualKeyboardV1) Keymap(format uint32, fd int, size uint32) error {
	const opcode = 0
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], format)
	l += 4
	client.PutUint32(_reqBuf[l:l+4], size)
	l += 4
	oob := unix.UnixRights(fd)
	err := i.Context().WriteMsg(_reqBuf[:], oob)
	return err
}

// Key sends a key event.
// time: timestamp with millisecond granularity
// key: evdev key code
// state: physical state of the key (0=released, 1=pressed)
func (i *ZwpVirtualKeyboardV1) Key(time, key, state uint32) error {
	const opcode = 1
	const _reqBufLen = 8 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], time)
	l += 4
	client.PutUint32(_reqBuf[l:l+4], key)
	l += 4
	client.PutUint32(_reqBuf[l:l+4], state)
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Modifiers updates modifier and group state.
// modsDepressed: depressed modifiers
// modsLatched: latched modifiers
// modsLocked: locked modifiers
// group: keyboard layout
func (i *ZwpVirtualKeyboardV1) Modifiers(modsDepressed, modsLatched, modsLocked, group uint32) error {
	const opcode = 2
	const _reqBufLen = 8 + 4 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], modsDepressed)
	l += 4
	client.PutUint32(_reqBuf[l:l+4], modsLatched)
	l += 4
	client.PutUint32(_reqBuf[l:l+4], modsLocked)
	l += 4
	client.PutUint32(_reqBuf[l:l+4], group)
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Destroy destroys the virtual keyboard object.
func (i *ZwpVirtualKeyboardV1) Destroy() error {
	const opcode = 3
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// ZwpVirtualKeyboardManagerV1 : virtual keyboard manager
//
// A virtual keyboard manager allows an application to provide keyboard
// input events as if they came from a physical keyboard.
type ZwpVirtualKeyboardManagerV1 struct {
	client.BaseProxy
}

// NewZwpVirtualKeyboardManagerV1 creates a new ZwpVirtualKeyboardManagerV1.
func NewZwpVirtualKeyboardManagerV1(ctx *client.Context) *ZwpVirtualKeyboardManagerV1 {
	zwpVirtualKeyboardManagerV1 := &ZwpVirtualKeyboardManagerV1{}
	ctx.Register(zwpVirtualKeyboardManagerV1)
	return zwpVirtualKeyboardManagerV1
}

// ZwpVirtualKeyboardManagerV1InterfaceName is the wayland interface name.
const ZwpVirtualKeyboardManagerV1InterfaceName = "zwp_virtual_keyboard_manager_v1"

// ZwpVirtualKeyboardManagerV1Error : error values
type ZwpVirtualKeyboardManagerV1Error uint32

const (
	ZwpVirtualKeyboardManagerV1ErrorUnauthorized ZwpVirtualKeyboardManagerV1Error = 0
)

// CreateVirtualKeyboard creates a new virtual keyboard associated to a seat.
// seat: the wl_seat to associate with
func (i *ZwpVirtualKeyboardManagerV1) CreateVirtualKeyboard(seat *client.Seat) (*ZwpVirtualKeyboardV1, error) {
	vk := NewZwpVirtualKeyboardV1(i.Context())
	const opcode = 0
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], seat.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], vk.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return vk, err
}
