// Code generated by go-wayland-scanner from wlr-virtual-pointer-unstable-v1.xml. DO NOT EDIT.

// wlr_virtual_pointer_unstable_v1 Protocol Copyright:
// Copyright © 2019 Josef Gajdusek
// SPDX-License-Identifier: MIT

package wlr_virtual_pointer

import (
	"github.com/vcaesar/go-wayland/client"
)

// ZwlrVirtualPointerV1 : virtual pointer
//
// This protocol allows clients to emulate a physical pointer device. The
// requests are mostly mirror opposites of those specified in wl_pointer.
type ZwlrVirtualPointerV1 struct {
	client.BaseProxy
}

// NewZwlrVirtualPointerV1 creates a new ZwlrVirtualPointerV1.
func NewZwlrVirtualPointerV1(ctx *client.Context) *ZwlrVirtualPointerV1 {
	zwlrVirtualPointerV1 := &ZwlrVirtualPointerV1{}
	ctx.Register(zwlrVirtualPointerV1)
	return zwlrVirtualPointerV1
}

// ZwlrVirtualPointerV1InterfaceName is the wayland interface name.
const ZwlrVirtualPointerV1InterfaceName = "zwlr_virtual_pointer_v1"

// ZwlrVirtualPointerV1Error : error values
type ZwlrVirtualPointerV1Error uint32

const (
	ZwlrVirtualPointerV1ErrorInvalidAxis       ZwlrVirtualPointerV1Error = 0
	ZwlrVirtualPointerV1ErrorInvalidAxisSource ZwlrVirtualPointerV1Error = 1
)

// Motion sends a pointer relative motion event.
// time: timestamp with millisecond granularity
// dx: displacement on the x-axis
// dy: displacement on the y-axis
func (i *ZwlrVirtualPointerV1) Motion(time uint32, dx, dy float64) error {
	const opcode = 0
	const _reqBufLen = 8 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], time)
	l += 4
	client.PutFixed(_reqBuf[l:l+4], dx)
	l += 4
	client.PutFixed(_reqBuf[l:l+4], dy)
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// MotionAbsolute sends a pointer absolute motion event.
// time: timestamp with millisecond granularity
// x: position on the x-axis
// y: position on the y-axis
// xExtent: extent of the x-axis
// yExtent: extent of the y-axis
func (i *ZwlrVirtualPointerV1) MotionAbsolute(time, x, y, xExtent, yExtent uint32) error {
	const opcode = 1
	const _reqBufLen = 8 + 4 + 4 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], time)
	l += 4
	client.PutUint32(_reqBuf[l:l+4], x)
	l += 4
	client.PutUint32(_reqBuf[l:l+4], y)
	l += 4
	client.PutUint32(_reqBuf[l:l+4], xExtent)
	l += 4
	client.PutUint32(_reqBuf[l:l+4], yExtent)
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Button sends a button press or release event.
// time: timestamp with millisecond granularity
// button: button that produced the event (Linux evdev code)
// state: physical state of the button (0=released, 1=pressed)
func (i *ZwlrVirtualPointerV1) Button(time, button, state uint32) error {
	const opcode = 2
	const _reqBufLen = 8 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], time)
	l += 4
	client.PutUint32(_reqBuf[l:l+4], button)
	l += 4
	client.PutUint32(_reqBuf[l:l+4], state)
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Axis sends scroll and other axis events.
// time: timestamp with millisecond granularity
// axis: axis type (0=vertical_scroll, 1=horizontal_scroll)
// value: length of vector in surface-local coordinates
func (i *ZwlrVirtualPointerV1) Axis(time, axis uint32, value float64) error {
	const opcode = 3
	const _reqBufLen = 8 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], time)
	l += 4
	client.PutUint32(_reqBuf[l:l+4], axis)
	l += 4
	client.PutFixed(_reqBuf[l:l+4], value)
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Frame indicates the set of events that logically belong together.
func (i *ZwlrVirtualPointerV1) Frame() error {
	const opcode = 4
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// AxisSource sends source information for scroll and other axes.
// axisSource: source of the axis event
func (i *ZwlrVirtualPointerV1) AxisSource(axisSource uint32) error {
	const opcode = 5
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], axisSource)
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// AxisStop sends axis stop event.
// time: timestamp with millisecond granularity
// axis: the axis stopped with this event
func (i *ZwlrVirtualPointerV1) AxisStop(time, axis uint32) error {
	const opcode = 6
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], time)
	l += 4
	client.PutUint32(_reqBuf[l:l+4], axis)
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// AxisDiscrete sends axis discrete step information.
// time: timestamp with millisecond granularity
// axis: axis type
// value: length of vector in surface-local coordinates
// discrete: number of steps
func (i *ZwlrVirtualPointerV1) AxisDiscrete(time, axis uint32, value float64, discrete int32) error {
	const opcode = 7
	const _reqBufLen = 8 + 4 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], time)
	l += 4
	client.PutUint32(_reqBuf[l:l+4], axis)
	l += 4
	client.PutFixed(_reqBuf[l:l+4], value)
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(discrete))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Destroy destroys the virtual pointer object.
func (i *ZwlrVirtualPointerV1) Destroy() error {
	const opcode = 8
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// ZwlrVirtualPointerManagerV1 : virtual pointer manager
//
// This object allows clients to create individual virtual pointer objects.
type ZwlrVirtualPointerManagerV1 struct {
	client.BaseProxy
}

// NewZwlrVirtualPointerManagerV1 creates a new ZwlrVirtualPointerManagerV1.
func NewZwlrVirtualPointerManagerV1(ctx *client.Context) *ZwlrVirtualPointerManagerV1 {
	zwlrVirtualPointerManagerV1 := &ZwlrVirtualPointerManagerV1{}
	ctx.Register(zwlrVirtualPointerManagerV1)
	return zwlrVirtualPointerManagerV1
}

// ZwlrVirtualPointerManagerV1InterfaceName is the wayland interface name.
const ZwlrVirtualPointerManagerV1InterfaceName = "zwlr_virtual_pointer_manager_v1"

// CreateVirtualPointer creates a new virtual pointer.
// seat: optional seat suggestion (may be nil proxy with ID 0)
func (i *ZwlrVirtualPointerManagerV1) CreateVirtualPointer(seat client.Proxy) (*ZwlrVirtualPointerV1, error) {
	vp := NewZwlrVirtualPointerV1(i.Context())
	var seatID uint32
	if seat != nil {
		seatID = seat.ID()
	}
	const opcode = 0
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], seatID)
	l += 4
	client.PutUint32(_reqBuf[l:l+4], vp.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return vp, err
}

// Destroy destroys the virtual pointer manager.
func (i *ZwlrVirtualPointerManagerV1) Destroy() error {
	const opcode = 1
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}
