// Code generated by go-wayland-scanner from wlr-screencopy-unstable-v1.xml. DO NOT EDIT.

// wlr_screencopy_unstable_v1 Protocol Copyright:
// Copyright © 2018 Simon Ser
// Copyright © 2019 Andri Yngvason
// SPDX-License-Identifier: MIT

package wlr_screencopy

import (
	"github.com/vcaesar/go-wayland/client"
)

// ZwlrScreencopyManagerV1 : manager to inform clients and begin capturing
type ZwlrScreencopyManagerV1 struct {
	client.BaseProxy
}

// NewZwlrScreencopyManagerV1 creates a new ZwlrScreencopyManagerV1.
func NewZwlrScreencopyManagerV1(ctx *client.Context) *ZwlrScreencopyManagerV1 {
	ret := &ZwlrScreencopyManagerV1{}
	ctx.Register(ret)
	return ret
}

// ZwlrScreencopyManagerV1InterfaceName is the wayland interface name.
const ZwlrScreencopyManagerV1InterfaceName = "zwlr_screencopy_manager_v1"

// CaptureOutput captures the next frame of an entire output.
// overlayCursor: composite cursor onto the frame (1=yes, 0=no)
// output: the wl_output to capture
func (i *ZwlrScreencopyManagerV1) CaptureOutput(overlayCursor int32, output *client.Output) (*ZwlrScreencopyFrameV1, error) {
	frame := NewZwlrScreencopyFrameV1(i.Context())
	const opcode = 0
	const _reqBufLen = 8 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], frame.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(overlayCursor))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], output.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return frame, err
}

// CaptureOutputRegion captures a region of an output.
func (i *ZwlrScreencopyManagerV1) CaptureOutputRegion(overlayCursor int32, output *client.Output, x, y, width, height int32) (*ZwlrScreencopyFrameV1, error) {
	frame := NewZwlrScreencopyFrameV1(i.Context())
	const opcode = 1
	const _reqBufLen = 8 + 4 + 4 + 4 + 4 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], frame.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(overlayCursor))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], output.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(x))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(y))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(width))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(height))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return frame, err
}

// Destroy destroys the screencopy manager.
func (i *ZwlrScreencopyManagerV1) Destroy() error {
	const opcode = 2
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// ZwlrScreencopyFrameV1 : a frame ready for copy
type ZwlrScreencopyFrameV1 struct {
	client.BaseProxy
	bufferHandler     ZwlrScreencopyFrameV1BufferHandlerFunc
	flagsHandler      ZwlrScreencopyFrameV1FlagsHandlerFunc
	readyHandler      ZwlrScreencopyFrameV1ReadyHandlerFunc
	failedHandler     ZwlrScreencopyFrameV1FailedHandlerFunc
	damageHandler     ZwlrScreencopyFrameV1DamageHandlerFunc
	bufferDoneHandler ZwlrScreencopyFrameV1BufferDoneHandlerFunc
}

// NewZwlrScreencopyFrameV1 creates a new ZwlrScreencopyFrameV1.
func NewZwlrScreencopyFrameV1(ctx *client.Context) *ZwlrScreencopyFrameV1 {
	ret := &ZwlrScreencopyFrameV1{}
	ctx.Register(ret)
	return ret
}

// ZwlrScreencopyFrameV1InterfaceName is the wayland interface name.
const ZwlrScreencopyFrameV1InterfaceName = "zwlr_screencopy_frame_v1"

// ZwlrScreencopyFrameV1Error : error values
type ZwlrScreencopyFrameV1Error uint32

const (
	ZwlrScreencopyFrameV1ErrorAlreadyUsed   ZwlrScreencopyFrameV1Error = 0
	ZwlrScreencopyFrameV1ErrorInvalidBuffer ZwlrScreencopyFrameV1Error = 1
)

// ZwlrScreencopyFrameV1Flags : frame flags
type ZwlrScreencopyFrameV1Flags uint32

const (
	ZwlrScreencopyFrameV1FlagsYInvert ZwlrScreencopyFrameV1Flags = 1
)

// --- Events ---

// ZwlrScreencopyFrameV1BufferEvent : wl_shm buffer information
type ZwlrScreencopyFrameV1BufferEvent struct {
	Format uint32 // buffer format (wl_shm.format)
	Width  uint32
	Height uint32
	Stride uint32
}

type ZwlrScreencopyFrameV1BufferHandlerFunc func(ZwlrScreencopyFrameV1BufferEvent)

func (i *ZwlrScreencopyFrameV1) SetBufferHandler(f ZwlrScreencopyFrameV1BufferHandlerFunc) {
	i.bufferHandler = f
}

// ZwlrScreencopyFrameV1FlagsEvent : frame flags
type ZwlrScreencopyFrameV1FlagsEvent struct {
	Flags uint32
}

type ZwlrScreencopyFrameV1FlagsHandlerFunc func(ZwlrScreencopyFrameV1FlagsEvent)

func (i *ZwlrScreencopyFrameV1) SetFlagsHandler(f ZwlrScreencopyFrameV1FlagsHandlerFunc) {
	i.flagsHandler = f
}

// ZwlrScreencopyFrameV1ReadyEvent : frame is available for reading
type ZwlrScreencopyFrameV1ReadyEvent struct {
	TvSecHi uint32
	TvSecLo uint32
	TvNsec  uint32
}

type ZwlrScreencopyFrameV1ReadyHandlerFunc func(ZwlrScreencopyFrameV1ReadyEvent)

func (i *ZwlrScreencopyFrameV1) SetReadyHandler(f ZwlrScreencopyFrameV1ReadyHandlerFunc) {
	i.readyHandler = f
}

// ZwlrScreencopyFrameV1FailedEvent : frame copy failed
type ZwlrScreencopyFrameV1FailedEvent struct{}

type ZwlrScreencopyFrameV1FailedHandlerFunc func(ZwlrScreencopyFrameV1FailedEvent)

func (i *ZwlrScreencopyFrameV1) SetFailedHandler(f ZwlrScreencopyFrameV1FailedHandlerFunc) {
	i.failedHandler = f
}

// ZwlrScreencopyFrameV1DamageEvent : damaged region
type ZwlrScreencopyFrameV1DamageEvent struct {
	X, Y, Width, Height uint32
}

type ZwlrScreencopyFrameV1DamageHandlerFunc func(ZwlrScreencopyFrameV1DamageEvent)

func (i *ZwlrScreencopyFrameV1) SetDamageHandler(f ZwlrScreencopyFrameV1DamageHandlerFunc) {
	i.damageHandler = f
}

// ZwlrScreencopyFrameV1BufferDoneEvent : all buffer types reported
type ZwlrScreencopyFrameV1BufferDoneEvent struct{}

type ZwlrScreencopyFrameV1BufferDoneHandlerFunc func(ZwlrScreencopyFrameV1BufferDoneEvent)

func (i *ZwlrScreencopyFrameV1) SetBufferDoneHandler(f ZwlrScreencopyFrameV1BufferDoneHandlerFunc) {
	i.bufferDoneHandler = f
}

// Dispatch dispatches events for ZwlrScreencopyFrameV1.
func (i *ZwlrScreencopyFrameV1) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0: // buffer
		if i.bufferHandler != nil {
			var e ZwlrScreencopyFrameV1BufferEvent
			l := 0
			e.Format = client.Uint32(data[l : l+4])
			l += 4
			e.Width = client.Uint32(data[l : l+4])
			l += 4
			e.Height = client.Uint32(data[l : l+4])
			l += 4
			e.Stride = client.Uint32(data[l : l+4])
			l += 4
			i.bufferHandler(e)
		}
	case 1: // flags
		if i.flagsHandler != nil {
			var e ZwlrScreencopyFrameV1FlagsEvent
			e.Flags = client.Uint32(data[0:4])
			i.flagsHandler(e)
		}
	case 2: // ready
		if i.readyHandler != nil {
			var e ZwlrScreencopyFrameV1ReadyEvent
			l := 0
			e.TvSecHi = client.Uint32(data[l : l+4])
			l += 4
			e.TvSecLo = client.Uint32(data[l : l+4])
			l += 4
			e.TvNsec = client.Uint32(data[l : l+4])
			l += 4
			i.readyHandler(e)
		}
	case 3: // failed
		if i.failedHandler != nil {
			i.failedHandler(ZwlrScreencopyFrameV1FailedEvent{})
		}
	case 4: // damage
		if i.damageHandler != nil {
			var e ZwlrScreencopyFrameV1DamageEvent
			l := 0
			e.X = client.Uint32(data[l : l+4])
			l += 4
			e.Y = client.Uint32(data[l : l+4])
			l += 4
			e.Width = client.Uint32(data[l : l+4])
			l += 4
			e.Height = client.Uint32(data[l : l+4])
			l += 4
			i.damageHandler(e)
		}
	case 5: // buffer_done
		if i.bufferDoneHandler != nil {
			i.bufferDoneHandler(ZwlrScreencopyFrameV1BufferDoneEvent{})
		}
	}
}

// --- Requests ---

// Copy copies the frame to the supplied buffer.
func (i *ZwlrScreencopyFrameV1) Copy(buffer *client.Buffer) error {
	const opcode = 0
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], buffer.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Destroy destroys the frame object.
func (i *ZwlrScreencopyFrameV1) Destroy() error {
	const opcode = 1
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// CopyWithDamage copies the frame when it's damaged.
func (i *ZwlrScreencopyFrameV1) CopyWithDamage(buffer *client.Buffer) error {
	const opcode = 2
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], buffer.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}
