// Code generated by go-wayland-scanner from wlr-foreign-toplevel-management-unstable-v1.xml. DO NOT EDIT.

// wlr_foreign_toplevel_management_unstable_v1 Protocol Copyright:
// Copyright © 2018 Ilia Bozhinov
// SPDX-License-Identifier: MIT

package wlr_foreign_toplevel

import (
	"github.com/vcaesar/go-wayland/client"
)

// ZwlrForeignToplevelManagerV1 : list and control opened apps
type ZwlrForeignToplevelManagerV1 struct {
	client.BaseProxy
	toplevelHandler ZwlrForeignToplevelManagerV1ToplevelHandlerFunc
	finishedHandler ZwlrForeignToplevelManagerV1FinishedHandlerFunc
}

// NewZwlrForeignToplevelManagerV1 creates a new ZwlrForeignToplevelManagerV1.
func NewZwlrForeignToplevelManagerV1(ctx *client.Context) *ZwlrForeignToplevelManagerV1 {
	ret := &ZwlrForeignToplevelManagerV1{}
	ctx.Register(ret)
	return ret
}

// ZwlrForeignToplevelManagerV1InterfaceName is the wayland interface name.
const ZwlrForeignToplevelManagerV1InterfaceName = "zwlr_foreign_toplevel_manager_v1"

// --- Manager Events ---

// ZwlrForeignToplevelManagerV1ToplevelEvent : a toplevel has been created
type ZwlrForeignToplevelManagerV1ToplevelEvent struct {
	Toplevel *ZwlrForeignToplevelHandleV1
}

type ZwlrForeignToplevelManagerV1ToplevelHandlerFunc func(ZwlrForeignToplevelManagerV1ToplevelEvent)

func (i *ZwlrForeignToplevelManagerV1) SetToplevelHandler(f ZwlrForeignToplevelManagerV1ToplevelHandlerFunc) {
	i.toplevelHandler = f
}

// ZwlrForeignToplevelManagerV1FinishedEvent : compositor is done
type ZwlrForeignToplevelManagerV1FinishedEvent struct{}

type ZwlrForeignToplevelManagerV1FinishedHandlerFunc func(ZwlrForeignToplevelManagerV1FinishedEvent)

func (i *ZwlrForeignToplevelManagerV1) SetFinishedHandler(f ZwlrForeignToplevelManagerV1FinishedHandlerFunc) {
	i.finishedHandler = f
}

// Dispatch dispatches events for ZwlrForeignToplevelManagerV1.
func (i *ZwlrForeignToplevelManagerV1) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0: // toplevel
		if i.toplevelHandler != nil {
			var e ZwlrForeignToplevelManagerV1ToplevelEvent
			id := client.Uint32(data[0:4])
			e.Toplevel = NewZwlrForeignToplevelHandleV1(i.Context(), id)
			i.toplevelHandler(e)
		}
	case 1: // finished
		if i.finishedHandler != nil {
			i.finishedHandler(ZwlrForeignToplevelManagerV1FinishedEvent{})
		}
	}
}

// Stop indicates the client no longer wishes to receive events for new toplevels.
func (i *ZwlrForeignToplevelManagerV1) Stop() error {
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// --- Toplevel Handle ---

// ZwlrForeignToplevelHandleV1State : toplevel state values
type ZwlrForeignToplevelHandleV1State uint32

const (
	ZwlrForeignToplevelHandleV1StateMaximized  ZwlrForeignToplevelHandleV1State = 0
	ZwlrForeignToplevelHandleV1StateMinimized  ZwlrForeignToplevelHandleV1State = 1
	ZwlrForeignToplevelHandleV1StateActivated  ZwlrForeignToplevelHandleV1State = 2
	ZwlrForeignToplevelHandleV1StateFullscreen ZwlrForeignToplevelHandleV1State = 3
)

// ZwlrForeignToplevelHandleV1 : an opened toplevel
type ZwlrForeignToplevelHandleV1 struct {
	client.BaseProxy
	titleHandler       ZwlrForeignToplevelHandleV1TitleHandlerFunc
	appIdHandler       ZwlrForeignToplevelHandleV1AppIdHandlerFunc
	stateHandler       ZwlrForeignToplevelHandleV1StateHandlerFunc
	doneHandler        ZwlrForeignToplevelHandleV1DoneHandlerFunc
	closedHandler      ZwlrForeignToplevelHandleV1ClosedHandlerFunc
	outputEnterHandler ZwlrForeignToplevelHandleV1OutputEnterHandlerFunc
	outputLeaveHandler ZwlrForeignToplevelHandleV1OutputLeaveHandlerFunc
	parentHandler      ZwlrForeignToplevelHandleV1ParentHandlerFunc
}

// NewZwlrForeignToplevelHandleV1 creates a handle from a server-sent new_id.
func NewZwlrForeignToplevelHandleV1(ctx *client.Context, id uint32) *ZwlrForeignToplevelHandleV1 {
	ret := &ZwlrForeignToplevelHandleV1{}
	ret.SetID(id)
	ret.SetContext(ctx)
	return ret
}

// ZwlrForeignToplevelHandleV1InterfaceName is the wayland interface name.
const ZwlrForeignToplevelHandleV1InterfaceName = "zwlr_foreign_toplevel_handle_v1"

// --- Handle Events ---

type ZwlrForeignToplevelHandleV1TitleEvent struct{ Title string }
type ZwlrForeignToplevelHandleV1TitleHandlerFunc func(ZwlrForeignToplevelHandleV1TitleEvent)

func (i *ZwlrForeignToplevelHandleV1) SetTitleHandler(f ZwlrForeignToplevelHandleV1TitleHandlerFunc) {
	i.titleHandler = f
}

type ZwlrForeignToplevelHandleV1AppIdEvent struct{ AppId string }
type ZwlrForeignToplevelHandleV1AppIdHandlerFunc func(ZwlrForeignToplevelHandleV1AppIdEvent)

func (i *ZwlrForeignToplevelHandleV1) SetAppIdHandler(f ZwlrForeignToplevelHandleV1AppIdHandlerFunc) {
	i.appIdHandler = f
}

type ZwlrForeignToplevelHandleV1OutputEnterEvent struct{ OutputID uint32 }
type ZwlrForeignToplevelHandleV1OutputEnterHandlerFunc func(ZwlrForeignToplevelHandleV1OutputEnterEvent)

func (i *ZwlrForeignToplevelHandleV1) SetOutputEnterHandler(f ZwlrForeignToplevelHandleV1OutputEnterHandlerFunc) {
	i.outputEnterHandler = f
}

type ZwlrForeignToplevelHandleV1OutputLeaveEvent struct{ OutputID uint32 }
type ZwlrForeignToplevelHandleV1OutputLeaveHandlerFunc func(ZwlrForeignToplevelHandleV1OutputLeaveEvent)

func (i *ZwlrForeignToplevelHandleV1) SetOutputLeaveHandler(f ZwlrForeignToplevelHandleV1OutputLeaveHandlerFunc) {
	i.outputLeaveHandler = f
}

type ZwlrForeignToplevelHandleV1StateEvent struct{ State []byte }
type ZwlrForeignToplevelHandleV1StateHandlerFunc func(ZwlrForeignToplevelHandleV1StateEvent)

func (i *ZwlrForeignToplevelHandleV1) SetStateHandler(f ZwlrForeignToplevelHandleV1StateHandlerFunc) {
	i.stateHandler = f
}

type ZwlrForeignToplevelHandleV1DoneEvent struct{}
type ZwlrForeignToplevelHandleV1DoneHandlerFunc func(ZwlrForeignToplevelHandleV1DoneEvent)

func (i *ZwlrForeignToplevelHandleV1) SetDoneHandler(f ZwlrForeignToplevelHandleV1DoneHandlerFunc) {
	i.doneHandler = f
}

type ZwlrForeignToplevelHandleV1ClosedEvent struct{}
type ZwlrForeignToplevelHandleV1ClosedHandlerFunc func(ZwlrForeignToplevelHandleV1ClosedEvent)

func (i *ZwlrForeignToplevelHandleV1) SetClosedHandler(f ZwlrForeignToplevelHandleV1ClosedHandlerFunc) {
	i.closedHandler = f
}

type ZwlrForeignToplevelHandleV1ParentEvent struct{ ParentID uint32 }
type ZwlrForeignToplevelHandleV1ParentHandlerFunc func(ZwlrForeignToplevelHandleV1ParentEvent)

func (i *ZwlrForeignToplevelHandleV1) SetParentHandler(f ZwlrForeignToplevelHandleV1ParentHandlerFunc) {
	i.parentHandler = f
}

// Dispatch dispatches events for ZwlrForeignToplevelHandleV1.
func (i *ZwlrForeignToplevelHandleV1) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0: // title
		if i.titleHandler != nil {
			var e ZwlrForeignToplevelHandleV1TitleEvent
			l := 0
			titleLen := int(client.Uint32(data[l : l+4]))
			l += 4
			if titleLen > 0 {
				e.Title = string(data[l : l+titleLen-1]) // strip trailing NUL
			}
			i.titleHandler(e)
		}
	case 1: // app_id
		if i.appIdHandler != nil {
			var e ZwlrForeignToplevelHandleV1AppIdEvent
			l := 0
			appIdLen := int(client.Uint32(data[l : l+4]))
			l += 4
			if appIdLen > 0 {
				e.AppId = string(data[l : l+appIdLen-1])
			}
			i.appIdHandler(e)
		}
	case 2: // output_enter
		if i.outputEnterHandler != nil {
			var e ZwlrForeignToplevelHandleV1OutputEnterEvent
			e.OutputID = client.Uint32(data[0:4])
			i.outputEnterHandler(e)
		}
	case 3: // output_leave
		if i.outputLeaveHandler != nil {
			var e ZwlrForeignToplevelHandleV1OutputLeaveEvent
			e.OutputID = client.Uint32(data[0:4])
			i.outputLeaveHandler(e)
		}
	case 4: // state
		if i.stateHandler != nil {
			var e ZwlrForeignToplevelHandleV1StateEvent
			l := 0
			stateLen := int(client.Uint32(data[l : l+4]))
			l += 4
			e.State = make([]byte, stateLen)
			copy(e.State, data[l:l+stateLen])
			i.stateHandler(e)
		}
	case 5: // done
		if i.doneHandler != nil {
			i.doneHandler(ZwlrForeignToplevelHandleV1DoneEvent{})
		}
	case 6: // closed
		if i.closedHandler != nil {
			i.closedHandler(ZwlrForeignToplevelHandleV1ClosedEvent{})
		}
	case 7: // parent
		if i.parentHandler != nil {
			var e ZwlrForeignToplevelHandleV1ParentEvent
			e.ParentID = client.Uint32(data[0:4])
			i.parentHandler(e)
		}
	}
}

// --- Handle Requests ---

// SetMaximized requests that the toplevel be maximized.
func (i *ZwlrForeignToplevelHandleV1) SetMaximized() error {
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	return i.Context().WriteMsg(_reqBuf[:], nil)
}

// UnsetMaximized requests that the toplevel be unmaximized.
func (i *ZwlrForeignToplevelHandleV1) UnsetMaximized() error {
	const opcode = 1
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	return i.Context().WriteMsg(_reqBuf[:], nil)
}

// SetMinimized requests that the toplevel be minimized.
func (i *ZwlrForeignToplevelHandleV1) SetMinimized() error {
	const opcode = 2
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	return i.Context().WriteMsg(_reqBuf[:], nil)
}

// UnsetMinimized requests that the toplevel be unminimized.
func (i *ZwlrForeignToplevelHandleV1) UnsetMinimized() error {
	const opcode = 3
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	return i.Context().WriteMsg(_reqBuf[:], nil)
}

// Activate requests that the toplevel be activated on the given seat.
func (i *ZwlrForeignToplevelHandleV1) Activate(seat *client.Seat) error {
	const opcode = 4
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], seat.ID())
	l += 4
	return i.Context().WriteMsg(_reqBuf[:], nil)
}

// Close requests that the toplevel close itself.
func (i *ZwlrForeignToplevelHandleV1) Close() error {
	const opcode = 5
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	return i.Context().WriteMsg(_reqBuf[:], nil)
}

// Destroy destroys the toplevel handle object.
func (i *ZwlrForeignToplevelHandleV1) Destroy() error {
	const opcode = 7
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	return i.Context().WriteMsg(_reqBuf[:], nil)
}

// SetFullscreen requests that the toplevel be fullscreened.
// output: optional output (may be nil)
func (i *ZwlrForeignToplevelHandleV1) SetFullscreen(output client.Proxy) error {
	var outputID uint32
	if output != nil {
		outputID = output.ID()
	}
	const opcode = 8
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], outputID)
	l += 4
	return i.Context().WriteMsg(_reqBuf[:], nil)
}

// UnsetFullscreen requests that the toplevel be unfullscreened.
func (i *ZwlrForeignToplevelHandleV1) UnsetFullscreen() error {
	const opcode = 9
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	return i.Context().WriteMsg(_reqBuf[:], nil)
}
